### ISSUE TITLE
`moon upgrade` does not upgrade the mooninfo on Windows

### ISSUE THREAD

**Issue by yj-qin** [moonbitlang/moon#105]
# Bug Report

### OS

Operating System: Windows 10

### MoonBit CLI Tools Version

```
moon 0.1.20240731 (0b8804b 2024-07-31) ~\.moon\bin\moon.exe
moonc v0.1.20240801+df82b9877 ~\.moon\bin\moonc.exe
moonrun 0.1.20240716 (08bce9c 2024-07-16) ~\.moon\bin\moonrun.exe
```

## Steps to Reproduce

Run `moon upgrade`

## Expected Behavior

Upgrade all toolchains correctly.

## Actual Behavior

Does not upgrade the mooninfo.exe.

## Checklist
- [x] (Optional) My case is minimal enough to be reproducible.

**Comment by Young-Flash** [comment]
thanks for report, the problem lies in https://github.com/moonbitlang/moon/blob/51b885cf0dd8af5975316e2f0d2e0777df0660b5/crates/moonbuild/src/upgrade.rs#L159-L168

miss `mooninfo` 😅
