### ISSUE TITLE
`moon publish` failed when the "source" is specified and more than one 'moon.pkg.json' occurred.

### ISSUE THREAD

**Issue by FlammeShadow** [moonbitlang/moon#141]
# Bug Report

### OS

Operating System: Windows

### MoonBit CLI Tools Version

```
moon 0.1.20240807 (235e4bc 2024-08-07) ~\.moon\bin\moon.exe
moonc v0.1.20240807+41236f720 ~\.moon\bin\moonc.exe
moonrun 0.1.20240716 (08bce9c 2024-07-16) ~\.moon\bin\moonrun.exe
```

## Steps to Reproduce

*NOTE*: I disconnected the network to prevent the publish command from succeeding and just run the check. 

```
moon new (use default configuration)
cd my-project
moon publish
```

## Expected Behavior

```
Running moon check ...
Check passed
```

In my projects which does not specify "source" in moon.mod.json, or only has one 'moon.pkg.json' , this works as expected.

## Actual Behavior

```
Running moon check ...
~\my-project\src\moon.pkg.json: cannot import `username/hello/lib` in `username/hello/src`, no such package
error: failed to run
```

**NOTE**: The package under `crates/tests/test_cases/specify_source_dir_001.in` (002 as well, I don't test the rest ones) reports similar error when execute `moon publish`.

## Checklist
- [ ] (Optional) My case is minimal enough to be reproducible.

**Comment by lijunchen** [comment]
Currently, the `moon publish` command is delegated to `mooncake publish`. However, I forgot to sync the related `source` field changes to `mooncake`.

This issue will be resolved after today’s release. I will notify you once it has been fixed.

**Comment by lijunchen** [comment]
This issue should be fixed after the following released version

```
$ moon version --all
moon 0.1.20240809 (e6f8c24 2024-08-09) ~/.moon/bin/moon
moonc v0.1.20240809+5c355ddde ~/.moon/bin/moonc
moonrun 0.1.20240716 (08bce9c 2024-07-16) ~/.moon/bin/moonrun
```
