### ISSUE TITLE
Bug: Internal compiler error

### ISSUE THREAD

**Issue by gmlewis** [moonbitlang/moon#194]
When running `moon test` on this repo:
https://github.com/gmlewis/moonbit-fonts

I get 428 errors that all look like this:

```shell
Error when running /Users/glenn/src/github.com/gmlewis/moonbit-fonts/target/wasm-gc/debug/test/fonts/fonts.internal_test.wasm: failed to execute 'moonrun /Users/glenn/src/github.com/gmlewis/moonbit-fonts/target/wasm-gc/debug/test/fonts/fonts.internal_test.wasm'
```

but VSCode doesn't show any errors in any of the `*.mbt` files.

**Comment by lijunchen** [comment]
We have improved `moon test`, now it has test block-level isolation and better error message. After upgrading `yj-qin/regexp` to version `0.2.5`, there are only 4 errors:

```
$ moon version --all
moon 0.1.20240823 (f608aa3 2024-08-23) ~/.moon/bin/moon
moonc v0.1.20240823+c622a5ab0 ~/.moon/bin/moonc
moonrun 0.1.20240822 (efda7a5 2024-08-22) ~/.moon/bin/moonrun

$ moon clean && moon test
test gmlewis/moonbit-fonts/fonts/split-path.mbt::split_path failed: ParseError("unable to parse SVG params 507 24")
test gmlewis/moonbit-fonts/fonts/gen-path.mbt::gen_path on some simple glyphs failed: ParseError("unable to parse SVG params 507 24")
test gmlewis/moonbit-fonts/fonts/parse-params.mbt::parse_params failed: ParseError("unable to parse SVG params  343 75 327.5 112 ")
test gmlewis/moonbit-fonts/fonts/translate-path.mbt::translate failed: ParseError("unable to parse SVG params 507 24")
```

These error messages should be sufficient for debugging.

Additionally, we have noticed that the process of generating test driver is very slow, and we are currently working on resolving this issue.

**Comment by gmlewis** [comment]
Thank you, @lijunchen - I'm still seeing some very odd behavior in this repo.
Even after I change the text in the ParseError statements and run `moon test` again, it always shows the old error message... which is very strange.  I've tried deleting the `target` and `.mooncakes` directories, then re-installed the `moon` compiler and ran `moon update && moon install`, and yet it still shows the _OLD_ error message even after I changed the string!
Very odd, and I have no clue why.

Also, when running VSCode on this repo, I can no longer run a test in the editor.  See screenshot:

![moon-test-2024-08-26_18-08-45](https://github.com/user-attachments/assets/cec17a2c-3832-44a3-8b83-4b748c10f24c)

**Comment by bzy-debug** [comment]
Maybe try to reload vscode or restart vscode extension host.

I'm using latest extension and cli on you repo. Everything seems good.

<img width="1234" alt="Screenshot 2024-08-27 at 14 41 42" src="https://github.com/user-attachments/assets/306eb13d-1e54-4c4e-a6e2-76e0cb14a0fd">

**Comment by lijunchen** [comment]
> Even after I change the text in the ParseError statements and run `moon test` again, it always shows the old error message... 

cannot reproduce in my local environment and GitHub Action😧

- <img width="1209" alt="1" src="https://github.com/user-attachments/assets/f578bd80-2185-4d51-907f-f149d0b73fc0">

- https://github.com/lijunchen/moonbit-fonts/actions/runs/10573057732/job/29291824917?pr=1#step:9:6

**Comment by gmlewis** [comment]
I just updated to:

```shell
$ moon version --all
moon 0.1.20240827 (f5f13e7 2024-08-27) ~/.moon/bin/moon
moonc v0.1.20240827+848d2bb76 ~/.moon/bin/moonc
moonrun 0.1.20240822 (efda7a5 2024-08-22) ~/.moon/bin/moonrun
```

and now everything is working again.  Thank you!

Closing.
