### ISSUE TITLE
Report a bug in the moon test cmd

### ISSUE THREAD

**Issue by guuzaa** [moonbitlang/moon#206]
# Bug Report

### OS

Operating System: Linux 4.19.112-2.el8.x86_64

### MoonBit CLI Tools Version

```
moon 0.1.20240823 (f608aa3 2024-08-23) ~/.moon/bin/moon
moonc v0.1.20240823+c622a5ab0 ~/.moon/bin/moonc
moonrun 0.1.20240822 (efda7a5 2024-08-22) ~/.moon/bin/moonrun
```

## Steps to Reproduce

1. Upgrade moon toolchain by `moon upgrade`.
2. Open the `core` repo by vscode. 
3. Run `moon test` in the terminal. 

## Expected Behavior
All test cases pass in no time.

## Actual Behavior
It takes a long time until most test cases failed as below.
![image](https://github.com/user-attachments/assets/ea8601db-82c5-4f16-a2ce-db7f75788386)

## Checklist
- [x] (Optional) My case is minimal enough to be reproducible.

**Comment by Young-Flash** [comment]
hi, have you try `moon clean` before `moon test`? maybe there are some artifact generated by old version toolchain

<img width="474" alt="image" src="https://github.com/user-attachments/assets/65dc5776-c78a-4dc8-baba-3f1557f7a3ce">

**Comment by guuzaa** [comment]
After I run `moon clean`, all test cases pass quickly.

**Comment by guuzaa** [comment]
Before that, when running `moon test --target wasm-gc -p moonbitlang/core/builtin -f array_test.mbt`, the test cases in which pass.
Why moon test is different from the one above? Why not let `moon test` clean old artifacts

**Comment by Young-Flash** [comment]
moon test will not clean old artifacts as we aim for an incremental build
