### ISSUE TITLE
Two tests fail when using the newest toolchain

### ISSUE THREAD

**Issue by lgxbslgx** [moonbitlang/moon#275]
# Bug Report

### OS

Operating System: Linux

### MoonBit CLI Tools Version

```
moon 0.1.20240902 (a1bf66a 2024-09-02) ~/.moon/bin/moon
moonc v0.1.20240902+47bcb87c9 ~/.moon/bin/moonc
moonrun 0.1.20240902 (a1bf66a 2024-09-02) ~/.moon/bin/moonrun
```

## Steps to Reproduce

```
$ moon upgrade

$ cargo test

// skip other information
failures:
    test_cases::test_deny_warn
    test_cases::test_moon_check_json_output
```

For `test_cases::test_deny_warn`, the order of the warnings is not right.

For ` test_cases::test_moon_check_json_output`, an unexpected `offset` field is outputted in the json.

## Expected Behavior

All tests should pass.

## Actual Behavior

Two tests fail.

## Checklist
- [x] (Optional) My case is minimal enough to be reproducible.

**Comment by lijunchen** [comment]
please try bleeding release?

```
curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash -s bleeding
```

**Comment by lgxbslgx** [comment]
> please try bleeding release?
> 
> ```
> curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash -s bleeding
> ```

I run the command locally and got a 404 error.

```
$ curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash -s bleeding
Downloading moonbit ...
curl: (22) The requested URL returned error: 404  #    #     #                

error: Failed to download moonbit from "https://cli.moonbitlang.cn/binaries/bleeding/moonbit-linux-x86_64.tar.gz"
```

**Comment by Young-Flash** [comment]
bleeding just for macos. the two failed tests will be fix by next release

**Comment by lgxbslgx** [comment]
> the two failed tests will be fix by next release

Got it. Thanks for your answers.

**Comment by Young-Flash** [comment]
should be fixed with the following release
```
moon 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moon
moonc v0.1.20240910+3af041b9a ~/.moon/bin/moonc
moonrun 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moonrun
```

**Comment by lgxbslgx** [comment]
> should be fixed with the following release
> 
> ```
> moon 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moon
> moonc v0.1.20240910+3af041b9a ~/.moon/bin/moonc
> moonrun 0.1.20240910 (0a5e0dc 2024-09-10) ~/.moon/bin/moonrun
> ```

The tests pass locally by using this release.
