### ISSUE TITLE
resolve empty `source` to project root

### ISSUE THREAD

**Issue by chawyehsu** [moonbitlang/moon#319]
## Problem

A `"source": ""` config in `moon.mod.json` raises an error of:

```
$ moon run .
error: failed to load `<path-redacted>/moon.mod.json`

Caused by:
    0: `source` bad format
    1: `source` should not be empty
```

Thought it would be treated as setting the source dir to the project root but it didn't work as I expected. The new template now contains a `"source": "src"` by default, which makes me intuitively conclude that removing the `src` string would let the project root be the source dir, which is in fact not.

## Expectation

As per [the JSON schema](https://moonbitlang.github.io/moon/json_schema.html) `source` in `moon.mod.json` is allowed to be the empty string, so `"source": ""`  is a valid config.

Rather than raising an error, I would expect `"source": ""` or ``"source": "."``  to be treated as setting the source dir to the project root, i.e. the dir `moon.mod.json` is located in, providing a more seamless configuration experience.

## Alternative

Currently, by removing the `source` field manually the same goal can be achieved.

**Comment by lijunchen** [comment]
> "source": "" or "source": "." to be treated as setting the source dir to the project root 

Sounds reasonable, I will fix it later
