### ISSUE TITLE
`moon bundle --target all` has concurrency bug

### ISSUE THREAD

**Issue by bzy-debug** [moonbitlang/moon#411]
# Bug Report

### OS

Operating System: macOs

### MoonBit CLI Tools Version

```
moon 0.1.20241021 (9d3a2d5 2024-10-21) ~/.moon/bin/moon
moonc v0.1.20241021+e6d54baa1 ~/.moon/bin/moonc
moonrun 0.1.20241021 (9d3a2d5 2024-10-21) ~/.moon/bin/moonrun
```

## Steps to Reproduce

run `moon bundle --target all` in core

## Expected Behavior

`target/pacakges.json` should always be valid json

## Actual Behavior

sometimes, `target/packages.json` might be invalid due to concurrent writing.

## Checklist
- [ ] (Optional) My case is minimal enough to be reproducible.

**Comment by Young-Flash** [comment]
closed by https://github.com/moonbitlang/moon/pull/412
