### ISSUE TITLE
empt moon.mod.json panic moon

### ISSUE THREAD

**Issue by HerrCai0907** [moonbitlang/moon#445]
# Bug Report

### OS

Operating System: macOS 

### MoonBit CLI Tools Version

```
moon 0.1.20241104 (62b13a6 2024-11-04) ~/.moon/bin/moon
moonc v0.1.20241104+8ce5d2967 ~/.moon/bin/moonc
moonrun 0.1.20241104 (62b13a6 2024-11-04) ~/.moon/bin/moonrun
```

## Steps to Reproduce

tree
```
├── LICENSE
├── README.md
├── moon.mod.json
└── src
    ├── main.mbt
    └── moon.pkg.json
```

moon.mod.json
```json
{
  "name": "",
  "version": "0.1.0",
  "readme": "README.md",
  "repository": "",
  "license": "Apache-2.0",
  "keywords": [],
  "description": "",
  "source": "src"
}
```

## Expected Behavior

give error message

## Actual Behavior

panic

## Checklist
- [x] (Optional) My case is minimal enough to be reproducible.

**Comment by Young-Flash** [comment]
closed by https://github.com/moonbitlang/moon/pull/446#event-15113104917
