### ISSUE TITLE
Test case under some path "src/main/*.mbt" is not recognized

### ISSUE THREAD

**Issue by iscas-zac** [moonbitlang/moon#498]
# Bug Report

### OS

Operating System: Windows

### MoonBit CLI Tools Version

```
\> moon version
moon 0.1.20241125 (6fe6396 2024-11-25)
```

## Steps to Reproduce

```powershell
\> moon version
moon 0.1.20241125 (6fe6396 2024-11-25)
\> moon new example
Initialized empty Git repository in /example/.git/
Created example
\> cd .\example\
\example> moon test
Total tests: 1, passed: 1, failed: 0.
\example> echo 'test "123" { assert_eq!(1, 1) }' >> src/main/main.mbt
\example> moon test
Total tests: 1, passed: 1, failed: 0.
\example> moon test --target wasm-gc -p username/hello/main -f main.mbt -i 0 -u
Warning: no test entry found
\example> moon test -p username/hello/main -f main.mbt -i 0 -u
Warning: no test entry found
```

## Expected Behavior

`moon test --target wasm-gc -p username/hello/main -f main.mbt -i 0 -u` is the default 'update test' action in VSCode plugin. It should update the test case in the `main.mbt` file.

## Actual Behavior

It reports "Warning: no test entry found" in the Output panel.

## Checklist
- [x] (Optional) My case is minimal enough to be reproducible.

**Comment by Young-Flash** [comment]
it's intentional, test block in main package in not support for now.

maybe we could have a better warn msg, like `Warning: no test entry found(test block in main package in not support for now)`

thanks for reporting
