### ISSUE TITLE
I'm curious, why not use OCaml but instead use Rust to write the build system?

### ISSUE THREAD

**Issue by Mng12345** [moonbitlang/moon#55]
As the title.

**Comment by lijunchen** [comment]
- moon has performance and cross-platform requirements, and Rust offers excellent performance and easier cross-platform development.
- Ecosystem: for example, Rust's [`clap`](https://github.com/clap-rs/clap) library makes writing command line applications very friendly, and there are foundational libraries like [`n2`](https://github.com/evmar/n2), which provide a solid starting point and reduce the work needed to build a robust build system from scratch.
- Rust has a larger developer community, we hope this will encourage more contributions and collaboration.

**Comment by yuyang-ok** [comment]
why not use `moonbit` itself?

**Comment by guuzaa** [comment]
I think bootstrapping needs time. Both Go and Rust used C to write their compilers at first.

**Comment by lijunchen** [comment]
- MoonBit does not currently support a native backend (may be available soon).
- The build system needs to call many system APIs and perform IO operations, which are not yet stable in MoonBit.
- Ecosystem, you can check the [Cargo.toml](https://github.com/moonbitlang/moon/blob/main/Cargo.toml), using MoonBit to complete these dependencies would require a significant amount of time. In this very early stage, our goal is to make it just work.
